[tool.poetry]
name = "lirpy"
version = "0.0.2"
description = ""
authors = ["Rob Nelson <nexisentertainment@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pillow = "^9.5.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.1"
black = {extras = ["d"], version = "^24.4.2"}
isort = "^5.13.2"
twine = "^5.1.1"

[tool.poetry.scripts]
lirpy = "lirpy.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
